### ISSUE TITLE
Improve or remove this project

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-nyan#2]
This project causes a lot of confusion for people who want to implement custom elements in bpmn-js. They end up asking the same questions in the forum again and again (e.g. "Why does this just replace service task?"). We should improve this project to clarify that this is more or less a "joke" or get rid of it and instead improve the [custom elements example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-elements).

**Comment by nikku** [comment]
I would not get rid of it, because it's a fun example of how to extend bpmn-js. 

Agreed though that it should clearly be marked as an example. We should probably link to the [custom elements example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-elements) you pointed to on top of the readme for more guidance on what is going on.

**Comment by nikku** [comment]
Could you give a reference where people ask about "Why does this just replace service task?" ?

**Comment by nikku** [comment]
This project is awesome.
